name: 'Amazon CodeArtifact Auth'
description: 'Logs in to the CodeArtifact for NPM(YARN) and Maven(Gradle).'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  region:
    description: 'AWS CodeArtifact Region'
    required: true
  domain:
    description: 'AWS CodeArtifact Domain Name'
    required: true
  owner:
    description: 'AWS CodeArtifact Owner Account Id'
    required: true
  duration:
    default: '900'
    description: 'Session duration'
    required: false
  type:
    description: 'CodeArtifact Repository Type. npm or gradle'
    required: true
  repo:
    description: 'CodeArtifact Repository Name'
    required: true
  npmrc-output-path:
    description: 'Directly where to store the .npmrc file'
    required: true
outputs:
  registry:
    description: 'The URI of the CodeArtifact repository'
  token:
    description: 'The Token for CodeArtifact'
runs:
  using: 'node16'
  main: 'dist/action/index.js'
  post: 'dist/cleanup/index.js'
